input <- read.table("household_power_consumption.txt",skip = 66637, nrow = 2880, sep = ";",col.names = colnames(read.table("household_power_consumption.txt",nrow = 1, header = TRUE, sep=";")))
date.time <- strptime(paste(input$Date, input$Time), format='%d/%m/%Y %H:%M:%S')
cbind(date.time,input)-> d
par(mfrow=c(2,2))
plot(d$date.time,d[,4],type="l",ylab="Global Active Power (kilowatts)",xlab="",xaxt="n")
axis(1, at=c(min(d$date.time), min(d$date.time)+86400,  min(d$date.time)+2*86400),labels=c("Thu", "Fri", "Sat")) 
plot(d$date.time,d$Voltage,type="l",ylab="voltage",xlab="datetime",xaxt="n")
axis(1, at=c(min(d$date.time), min(d$date.time)+86400,  min(d$date.time)+2*86400),labels=c("Thu", "Fri", "Sat")) 
plot(d$date.time,d$Sub_metering_1,type="l",ylab="Global Active Power (kilowatts)",xlab="",xaxt="n", ylim=range(c(d$Sub_metering_1,d$Sub_metering_2,d$Sub_metering_3)))
par(new=TRUE)
plot(d$date.time,d$Sub_metering_2,type="l", ylim=range(c(d$Sub_metering_1,d$Sub_metering_2,d$Sub_metering_3)), axes = FALSE, xlab = "", ylab = "",col="red")
par(new=TRUE)
plot(d$date.time,d$Sub_metering_3,type="l", ylim=range(c(d$Sub_metering_1,d$Sub_metering_2,d$Sub_metering_3)), axes = FALSE, xlab = "", ylab = "",col="blue")
legend("topright",col=c("black","red","blue"),pch= "_",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
axis(1, at=c(min(d$date.time), min(d$date.time)+86400,  min(d$date.time)+2*86400),labels=c("Thu", "Fri", "Sat")) 
plot(d$date.time,d$Global_reactive_power,type="l",ylab="Global_reactive_power",xlab="datetime",xaxt="n")
axis(1, at=c(min(d$date.time), min(d$date.time)+86400,  min(d$date.time)+2*86400),labels=c("Thu", "Fri", "Sat")) 
dev.copy(png,file="plot4.png")
dev.off()
